### PR TITLE
Use encoding

### PR DESCRIPTION
**Pull request by slibs63**

### CODE REVIEW

**Comment by alin-luminoso** [comment]
Er, I know this went back and forth, but I'm pretty sure what's left is not what you meant to have happen...

**Comment by slibs63** [comment]
Oy vey.  To clarify, we've decided we're not specifying encoding in `open()` statements due to incompatibility with Py2, but we are specifying utf-8 in any remaining `json.load()` statements?

**Comment by alin-luminoso** [comment]
Hmm.

So, I think what's going on with the code in 117-118 is this...

* It's right (enough) in Py2, where `open()` with no mode just says "read as a bytestring but do newline conversion":
```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> open('out.txt').read()
'\xf0\x9f\x90\xbc'
```

* It's not really right in Py3, if the locale encoding is not UTF-8, for the reasons we're used to:
```
(lumi)alin@analytics-0:~/tmp$ python
Python 3.4.0 (default, Jun 19 2015, 14:20:21) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> open('out.txt').read()
'🐼'
>>> 
(lumi)alin@analytics-0:~/tmp$ export LANG=en_US.windows-1252
(lumi)alin@analytics-0:~/tmp$ python
Python 3.4.0 (default, Jun 19 2015, 14:20:21) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> open('out.txt').read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/net/massave-users/alin/.virtualenvs/lumi/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 0: ordinal not in range(128)
```

This suggests that we need some kind of compatibility module type solution.

The function in 240 was already right, because it only runs in Py3.

**Comment by slibs63** [comment]
Ah, right, I neglected to read the function name in line 240.  I may need to save the rest for 2016.

**Comment by alin-luminoso** [comment]
Wait, it's going to take until _next year_ to--

(okay I'll go now)

**Comment by Tahnan** [comment]
If this does get revived, don't forget to also change the CHANGELOG and bump up the version number.  (And merge in master first, where those two things have changed.)

**Comment by luminosamaz** [comment]
We only support python 3 now per our documentation.

**Pull request closed without merging**
